#!/usr/bin/env bash

set -euo pipefail

source .github/scripts/cloud_run_env.sh
cloud_run_set_defaults

bash .github/scripts/validate_cloud_run_deploy_env.sh

env_vars=(
  "POLICYENGINE_DB_INSTANCE_CONNECTION_NAME=${POLICYENGINE_DB_INSTANCE_CONNECTION_NAME}"
  "POLICYENGINE_DB_USER=${POLICYENGINE_DB_USER:-policyengine}"
  "POLICYENGINE_DB_NAME=${POLICYENGINE_DB_NAME:-policyengine}"
  "GATEWAY_AUTH_REQUIRED=1"
  "GATEWAY_AUTH_ISSUER=${GATEWAY_AUTH_ISSUER}"
  "GATEWAY_AUTH_AUDIENCE=${GATEWAY_AUTH_AUDIENCE}"
  "GATEWAY_AUTH_CLIENT_ID=${GATEWAY_AUTH_CLIENT_ID}"
  "GATEWAY_AUTH_CLIENT_SECRET_RESOURCE=${GATEWAY_AUTH_CLIENT_SECRET_RESOURCE}"
  "SIM_ENTRYPOINT=${SIM_ENTRYPOINT}"
  "ROUTE_IMPL_HEALTH=${ROUTE_IMPL_HEALTH}"
  "ROUTE_IMPL_SPECIFICATION=${ROUTE_IMPL_SPECIFICATION}"
  "ROUTE_IMPL_METADATA=${ROUTE_IMPL_METADATA}"
  "ROUTE_IMPL_POLICY=${ROUTE_IMPL_POLICY}"
  "DB_READ_POLICY=${DB_READ_POLICY}"
  "DB_WRITE_POLICY=${DB_WRITE_POLICY}"
  "SIM_COMPUTE_ECONOMY=old_gateway"
  "CLOUD_RUN_REVISION_TAG=${CLOUD_RUN_TAG}"
  "WEB_CONCURRENCY=${CLOUD_RUN_WEB_CONCURRENCY}"
  "RUNTIME_CACHE_MODE=deployed"
  "RUNTIME_CACHE_ENVIRONMENT=${CLOUD_RUN_RUNTIME_CACHE_ENVIRONMENT}"
  "RUNTIME_CACHE_SERVICE=api"
  "V2_SUPABASE_PROJECT_REF=${V2_SUPABASE_PROJECT_REF}"
  "V2_SUPABASE_ENVIRONMENT=${V2_SUPABASE_ENVIRONMENT}"
  "V2_RUNTIME_DATABASE_URL_SECRET_RESOURCE=${V2_RUNTIME_DATABASE_URL_SECRET_RESOURCE}"
)

if [[ -n "${OLD_SIMULATION_GATEWAY_URL:-}" ]]; then
  env_vars+=("OLD_SIMULATION_GATEWAY_URL=${OLD_SIMULATION_GATEWAY_URL}")
fi
if [[ -n "${SIMULATION_ENTRYPOINT_URL:-}" ]]; then
  env_vars+=("SIMULATION_ENTRYPOINT_URL=${SIMULATION_ENTRYPOINT_URL}")
fi

secret_vars=(
  "POLICYENGINE_DB_PASSWORD=${CLOUD_RUN_POLICYENGINE_DB_PASSWORD_SECRET}"
  "POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN=${CLOUD_RUN_GITHUB_MICRODATA_TOKEN_SECRET}"
  "OPENAI_API_KEY=${CLOUD_RUN_OPENAI_API_KEY_SECRET}"
  "HUGGING_FACE_TOKEN=${CLOUD_RUN_HUGGING_FACE_TOKEN_SECRET}"
  "RUNTIME_CACHE_URL=${CLOUD_RUN_RUNTIME_CACHE_URL_SECRET}"
  "RUNTIME_CACHE_CA_CERT=${CLOUD_RUN_RUNTIME_CACHE_CA_CERT_SECRET}"
)

set_env_vars="$(IFS='|'; echo "^|^${env_vars[*]}")"
set_secret_vars="$(IFS='|'; echo "^|^${secret_vars[*]}")"

cloud_run_run gcloud run deploy "${CLOUD_RUN_SERVICE}" \
  --project "${CLOUD_RUN_PROJECT}" \
  --region "${CLOUD_RUN_REGION}" \
  --platform managed \
  --image "${CLOUD_RUN_IMAGE_URI}" \
  --tag "${CLOUD_RUN_TAG}" \
  --no-traffic \
  --allow-unauthenticated \
  --execution-environment gen2 \
  --network "${CLOUD_RUN_VPC_NETWORK}" \
  --subnet "${CLOUD_RUN_VPC_SUBNET}" \
  --vpc-egress "${CLOUD_RUN_VPC_EGRESS}" \
  --service-account "${CLOUD_RUN_RUNTIME_SERVICE_ACCOUNT}" \
  --add-cloudsql-instances "${POLICYENGINE_DB_INSTANCE_CONNECTION_NAME}" \
  --port "${CLOUD_RUN_PORT}" \
  --cpu "${CLOUD_RUN_CPU}" \
  --cpu-boost \
  --memory "${CLOUD_RUN_MEMORY}" \
  --timeout "${CLOUD_RUN_TIMEOUT}" \
  --min-instances "${CLOUD_RUN_MIN_INSTANCES}" \
  --min "${CLOUD_RUN_SERVICE_MIN_INSTANCES}" \
  --max-instances "${CLOUD_RUN_MAX_INSTANCES}" \
  --concurrency "${CLOUD_RUN_CONCURRENCY}" \
  --startup-probe "${CLOUD_RUN_STARTUP_PROBE}" \
  --set-env-vars "${set_env_vars}" \
  --set-secrets "${set_secret_vars}"
