runtime: custom
env: flex
resources:
  cpu: 24
  memory_gb: 128
  disk_size_gb: 128
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8
liveness_check:
  path: "/liveness-check"
  check_interval_sec: 30
  timeout_sec: 30
  failure_threshold: 5
  success_threshold: 2
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "22"
readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 400
