runtime: custom
env: flex
resources:
  cpu: 1
  memory_gb: 6
  disk_size_gb: 32
automatic_scaling:
  min_num_instances: 2
  max_num_instances: 4
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
