runtime: custom
service: policyengine-api-test
env: flex
resources:
  cpu: 4
  memory_gb: 18
  disk_size_gb: 64
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8
liveness_check:
  check_interval_sec: 30
  timeout_sec: 30
  failure_threshold: 10
  success_threshold: 1
