"""use native UUID report run idempotency keys

Revision ID: 4faee127fa16
Revises: 5f048586d8f1
Create Date: 2026-08-18 16:20:46.343261
Generation: uv run alembic -c alembic-v2.ini revision --autogenerate
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "4faee127fa16"
down_revision: Union[str, None] = "5f048586d8f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Post-generation correction: the text-only check must be removed before
    # the type change, and PostgreSQL requires an explicit text-to-UUID cast.
    op.drop_constraint(
        op.f("ck_report_runs_idempotency_key_nonblank"),
        "report_runs",
        type_="check",
    )
    op.alter_column(
        "report_runs",
        "idempotency_key",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Uuid(),
        existing_nullable=True,
        postgresql_using="idempotency_key::uuid",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Post-generation correction: cast UUIDs back to text before restoring the
    # text-only check constraint.
    op.alter_column(
        "report_runs",
        "idempotency_key",
        existing_type=sa.Uuid(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
        postgresql_using="idempotency_key::text",
    )
    op.create_check_constraint(
        op.f("ck_report_runs_idempotency_key_nonblank"),
        "report_runs",
        "idempotency_key IS NULL OR length(TRIM(BOTH FROM idempotency_key)) > 0",
    )
    # ### end Alembic commands ###
