"""constrain v2 user country and report idempotency

Revision ID: 5f048586d8f1
Revises: b4c69674dd47
Create Date: 2026-08-18 12:54:00.963782
Generation: uv run alembic -c alembic-v2.ini revision --autogenerate
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "5f048586d8f1"
down_revision: Union[str, None] = "b4c69674dd47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_report_runs_idempotency_key_nonblank"),
        "report_runs",
        "idempotency_key IS NULL OR length(trim(idempotency_key)) > 0",
    )
    op.add_column(
        "users",
        sa.Column(
            "primary_country",
            sqlmodel.sql.sqltypes.AutoString(length=2),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        op.f("ck_users_primary_country"), "users", "primary_country IN ('us', 'uk')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_users_primary_country"), "users", type_="check")
    op.drop_column("users", "primary_country")
    op.drop_constraint(
        op.f("ck_report_runs_idempotency_key_nonblank"), "report_runs", type_="check"
    )
    # ### end Alembic commands ###
