"""version metadata catalog snapshots

Revision ID: 68b4a5ae5dc5
Revises: f5ef4347cb2a
Create Date: 2026-08-21 02:13:03.270478
Generation: uv run alembic -c alembic-v2.ini revision --autogenerate
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "68b4a5ae5dc5"
down_revision: Union[str, None] = "f5ef4347cb2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datasets", sa.Column("tax_benefit_model_version_id", sa.Uuid(), nullable=False)
    )
    op.add_column(
        "regions", sa.Column("tax_benefit_model_version_id", sa.Uuid(), nullable=False)
    )
    op.drop_constraint(
        op.f("fk_regions_default_dataset_model_datasets"), "regions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_datasets_tax_benefit_model_id"), table_name="datasets")
    op.drop_constraint(op.f("uq_datasets_id_model"), "datasets", type_="unique")
    op.drop_constraint(op.f("uq_datasets_model_name"), "datasets", type_="unique")
    op.create_index(
        op.f("ix_datasets_tax_benefit_model_version_id"),
        "datasets",
        ["tax_benefit_model_version_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_datasets_id_model_version",
        "datasets",
        ["id", "tax_benefit_model_version_id"],
    )
    op.create_unique_constraint(
        "uq_datasets_model_version_name",
        "datasets",
        ["tax_benefit_model_version_id", "name"],
    )
    op.drop_constraint(
        op.f("fk_datasets_tax_benefit_model_id_tax_benefit_models"),
        "datasets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_datasets_tax_benefit_model_version_id_tax_benefit_model_versions"),
        "datasets",
        "tax_benefit_model_versions",
        ["tax_benefit_model_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("datasets", "tax_benefit_model_id")
    op.create_index(
        "uq_parameter_values_canonical_parameter_start_date",
        "parameter_values",
        ["parameter_id", "start_date"],
        unique=True,
        postgresql_where=sa.text("policy_id IS NULL AND dynamic_id IS NULL"),
        sqlite_where=sa.text("policy_id IS NULL AND dynamic_id IS NULL"),
    )
    op.drop_index(op.f("ix_regions_tax_benefit_model_id"), table_name="regions")
    op.drop_constraint(op.f("uq_regions_model_code"), "regions", type_="unique")
    op.create_index(
        op.f("ix_regions_tax_benefit_model_version_id"),
        "regions",
        ["tax_benefit_model_version_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_regions_model_version_code",
        "regions",
        ["tax_benefit_model_version_id", "code"],
    )
    op.drop_constraint(
        op.f("fk_regions_tax_benefit_model_id_tax_benefit_models"),
        "regions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_regions_default_dataset_model_version",
        "regions",
        "datasets",
        ["default_dataset_id", "tax_benefit_model_version_id"],
        ["id", "tax_benefit_model_version_id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_regions_tax_benefit_model_version_id_tax_benefit_model_versions"),
        "regions",
        "tax_benefit_model_versions",
        ["tax_benefit_model_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("regions", "tax_benefit_model_id")
    op.add_column(
        "tax_benefit_model_versions",
        sa.Column("current_law_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "tax_benefit_model_versions",
        sa.Column("metadata_time_periods", sa.JSON(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tax_benefit_model_versions", "metadata_time_periods")
    op.drop_column("tax_benefit_model_versions", "current_law_id")
    op.add_column(
        "datasets",
        sa.Column(
            "tax_benefit_model_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "regions",
        sa.Column(
            "tax_benefit_model_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_regions_tax_benefit_model_version_id_tax_benefit_model_versions"),
        "regions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_regions_default_dataset_model_version", "regions", type_="foreignkey"
    )
    op.drop_constraint("uq_regions_model_version_code", "regions", type_="unique")
    op.drop_index(op.f("ix_regions_tax_benefit_model_version_id"), table_name="regions")
    op.drop_constraint(
        op.f("fk_datasets_tax_benefit_model_version_id_tax_benefit_model_versions"),
        "datasets",
        type_="foreignkey",
    )
    op.drop_constraint("uq_datasets_model_version_name", "datasets", type_="unique")
    op.drop_constraint("uq_datasets_id_model_version", "datasets", type_="unique")
    op.drop_index(
        op.f("ix_datasets_tax_benefit_model_version_id"), table_name="datasets"
    )
    op.create_foreign_key(
        op.f("fk_datasets_tax_benefit_model_id_tax_benefit_models"),
        "datasets",
        "tax_benefit_models",
        ["tax_benefit_model_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_unique_constraint(
        op.f("uq_datasets_model_name"),
        "datasets",
        ["tax_benefit_model_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_datasets_id_model"),
        "datasets",
        ["id", "tax_benefit_model_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_datasets_tax_benefit_model_id"),
        "datasets",
        ["tax_benefit_model_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_regions_tax_benefit_model_id_tax_benefit_models"),
        "regions",
        "tax_benefit_models",
        ["tax_benefit_model_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_regions_default_dataset_model_datasets"),
        "regions",
        "datasets",
        ["default_dataset_id", "tax_benefit_model_id"],
        ["id", "tax_benefit_model_id"],
        ondelete="RESTRICT",
    )
    op.create_unique_constraint(
        op.f("uq_regions_model_code"),
        "regions",
        ["tax_benefit_model_id", "code"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_regions_tax_benefit_model_id"),
        "regions",
        ["tax_benefit_model_id"],
        unique=False,
    )
    op.drop_column("regions", "tax_benefit_model_version_id")
    op.drop_column("datasets", "tax_benefit_model_version_id")
    op.drop_index(
        "uq_parameter_values_canonical_parameter_start_date",
        table_name="parameter_values",
        postgresql_where=sa.text("policy_id IS NULL AND dynamic_id IS NULL"),
        sqlite_where=sa.text("policy_id IS NULL AND dynamic_id IS NULL"),
    )
    # ### end Alembic commands ###
