"""migrate v2 policies

Revision ID: 711ec2f0a5a5
Revises: 68b4a5ae5dc5
Create Date: 2026-09-01 16:17:04.855675
Generation: uv run alembic -c alembic-v2.ini revision --autogenerate
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = "711ec2f0a5a5"
down_revision: Union[str, None] = "68b4a5ae5dc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parameter_values",
        "value_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        "uq_parameter_values_policy_parameter_start_date",
        "parameter_values",
        ["policy_id", "parameter_id", "start_date"],
    )
    op.create_check_constraint(
        op.f("ck_parameter_values_effective_period"),
        "parameter_values",
        "end_date IS NULL OR end_date >= start_date",
    )
    op.add_column(
        "policies",
        sa.Column(
            "country_id", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False
        ),
    )
    op.add_column(
        "policies", sa.Column("tax_benefit_model_version_id", sa.Uuid(), nullable=False)
    )
    op.add_column(
        "policies", sa.Column("canonicalization_version", sa.Integer(), nullable=False)
    )
    op.add_column(
        "policies",
        sa.Column(
            "content_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
    )
    op.create_index(
        "ix_policies_country_model",
        "policies",
        ["country_id", "tax_benefit_model_id"],
        unique=False,
    )
    op.create_index(
        "ix_policies_country_model_version",
        "policies",
        ["country_id", "tax_benefit_model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policies_tax_benefit_model_version_id"),
        "policies",
        ["tax_benefit_model_version_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_policies_canonicalization_content_hash",
        "policies",
        ["canonicalization_version", "content_hash"],
    )
    op.create_unique_constraint(
        "uq_policies_id_country", "policies", ["id", "country_id"]
    )
    op.create_foreign_key(
        op.f("fk_policies_tax_benefit_model_version_id_tax_benefit_model_versions"),
        "policies",
        "tax_benefit_model_versions",
        ["tax_benefit_model_version_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        op.f("ck_policies_canonicalization_version"),
        "policies",
        "canonicalization_version > 0",
    )
    op.create_check_constraint(
        op.f("ck_policies_content_hash_length"), "policies", "length(content_hash) = 64"
    )
    op.create_check_constraint(
        op.f("ck_policies_country"), "policies", "country_id IN ('us', 'uk')"
    )
    op.drop_column("policies", "name")
    op.drop_column("policies", "description")
    # Post-generation correction: the generated mapping table preceded the
    # composite policy key referenced by its foreign key.
    op.create_table(
        "legacy_policy_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "country_id", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False
        ),
        sa.Column("legacy_policy_id", sa.BigInteger(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_policy_hash",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.CheckConstraint(
            "country_id IN ('us', 'uk')", name=op.f("ck_legacy_policy_mappings_country")
        ),
        sa.ForeignKeyConstraint(
            ["policy_id", "country_id"],
            ["policies.id", "policies.country_id"],
            name="fk_legacy_policy_mappings_policy_country",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legacy_policy_mappings")),
        sa.UniqueConstraint(
            "country_id",
            "legacy_policy_id",
            name="uq_legacy_policy_mappings_country_legacy",
        ),
    )
    op.create_index(
        "ix_legacy_policy_mappings_policy",
        "legacy_policy_mappings",
        ["policy_id"],
        unique=False,
    )
    op.add_column(
        "user_policies",
        sa.Column(
            "country_id", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False
        ),
    )
    op.add_column(
        "user_policies",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    )
    op.add_column("user_policies", sa.Column("description", sa.Text(), nullable=True))
    # Post-generation correction: PostgreSQL cannot change the source type
    # while its UUID foreign key remains in place.
    op.drop_constraint(
        op.f("fk_user_policies_user_id_users"), "user_policies", type_="foreignkey"
    )
    op.alter_column(
        "user_policies",
        "user_id",
        existing_type=sa.UUID(),
        type_=sqlmodel.sql.sqltypes.AutoString(length=255),
        existing_nullable=False,
        postgresql_using="user_id::text",
    )
    op.drop_constraint(
        op.f("uq_user_policies_user_policy"), "user_policies", type_="unique"
    )
    op.create_index(
        "ix_user_policies_country_policy",
        "user_policies",
        ["country_id", "policy_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_policies_country_user_created_id",
        "user_policies",
        ["country_id", "user_id", "created_at", "id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_user_policies_id_country", "user_policies", ["id", "country_id"]
    )
    op.drop_constraint(
        op.f("fk_user_policies_policy_id_policies"), "user_policies", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_user_policies_policy_country",
        "user_policies",
        "policies",
        ["policy_id", "country_id"],
        ["id", "country_id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        op.f("ck_user_policies_country"), "user_policies", "country_id IN ('us', 'uk')"
    )
    op.drop_column("user_policies", "country")
    op.drop_column("user_policies", "label")
    # Post-generation correction: this mapping likewise depends on the new
    # association composite key.
    op.create_table(
        "legacy_user_policy_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "country_id", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False
        ),
        sa.Column("legacy_user_policy_id", sa.BigInteger(), nullable=False),
        sa.Column("user_policy_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint_version", sa.Integer(), nullable=False),
        sa.Column(
            "fingerprint_sha256",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.CheckConstraint(
            "country_id IN ('us', 'uk')",
            name=op.f("ck_legacy_user_policy_mappings_country"),
        ),
        sa.CheckConstraint(
            "fingerprint_version > 0",
            name=op.f("ck_legacy_user_policy_mappings_fingerprint_version"),
        ),
        sa.CheckConstraint(
            "length(fingerprint_sha256) = 64",
            name=op.f("ck_legacy_user_policy_mappings_fingerprint_length"),
        ),
        sa.ForeignKeyConstraint(
            ["user_policy_id", "country_id"],
            ["user_policies.id", "user_policies.country_id"],
            name="fk_legacy_user_policy_mappings_association_country",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legacy_user_policy_mappings")),
        sa.UniqueConstraint(
            "country_id",
            "legacy_user_policy_id",
            name="uq_legacy_user_policy_mappings_country_legacy",
        ),
        sa.UniqueConstraint(
            "user_policy_id", name="uq_legacy_user_policy_mappings_association"
        ),
    )
    op.create_index(
        "ix_legacy_user_policy_mappings_association",
        "legacy_user_policy_mappings",
        ["user_policy_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Post-generation correction: dependent mappings must be removed before
    # their referenced composite keys.
    op.drop_index(
        "ix_legacy_user_policy_mappings_association",
        table_name="legacy_user_policy_mappings",
    )
    op.drop_table("legacy_user_policy_mappings")
    op.drop_index(
        "ix_legacy_policy_mappings_policy", table_name="legacy_policy_mappings"
    )
    op.drop_table("legacy_policy_mappings")
    op.add_column(
        "user_policies",
        sa.Column("label", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_policies",
        sa.Column(
            "country", sa.VARCHAR(length=16), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(op.f("ck_user_policies_country"), "user_policies", type_="check")
    op.drop_constraint(
        "fk_user_policies_policy_country", "user_policies", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_user_policies_policy_id_policies"),
        "user_policies",
        "policies",
        ["policy_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_user_policies_id_country", "user_policies", type_="unique")
    op.drop_index(
        "ix_user_policies_country_user_created_id", table_name="user_policies"
    )
    op.drop_index("ix_user_policies_country_policy", table_name="user_policies")
    op.create_unique_constraint(
        op.f("uq_user_policies_user_policy"),
        "user_policies",
        ["user_id", "policy_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "user_policies",
        "user_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="user_id::uuid",
    )
    op.create_foreign_key(
        op.f("fk_user_policies_user_id_users"),
        "user_policies",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("user_policies", "description")
    op.drop_column("user_policies", "name")
    op.drop_column("user_policies", "country_id")
    op.add_column(
        "policies",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "policies",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("ck_policies_country"), "policies", type_="check")
    op.drop_constraint(
        op.f("ck_policies_content_hash_length"), "policies", type_="check"
    )
    op.drop_constraint(
        op.f("ck_policies_canonicalization_version"), "policies", type_="check"
    )
    op.drop_constraint(
        op.f("fk_policies_tax_benefit_model_version_id_tax_benefit_model_versions"),
        "policies",
        type_="foreignkey",
    )
    op.drop_constraint("uq_policies_id_country", "policies", type_="unique")
    op.drop_constraint(
        "uq_policies_canonicalization_content_hash", "policies", type_="unique"
    )
    op.drop_index(
        op.f("ix_policies_tax_benefit_model_version_id"), table_name="policies"
    )
    op.drop_index("ix_policies_country_model_version", table_name="policies")
    op.drop_index("ix_policies_country_model", table_name="policies")
    op.drop_column("policies", "content_hash")
    op.drop_column("policies", "canonicalization_version")
    op.drop_column("policies", "tax_benefit_model_version_id")
    op.drop_column("policies", "country_id")
    op.drop_constraint(
        op.f("ck_parameter_values_effective_period"), "parameter_values", type_="check"
    )
    op.drop_constraint(
        "uq_parameter_values_policy_parameter_start_date",
        "parameter_values",
        type_="unique",
    )
    op.alter_column(
        "parameter_values",
        "value_json",
        existing_type=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
