"""migrate v2 households

Revision ID: 724b1b11a33e
Revises: af34023a728f
Create Date: 2026-09-07 23:40:07.666694
Generation: uv run alembic -c alembic-v2.ini revision --autogenerate
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = "724b1b11a33e"
down_revision: Union[str, None] = "af34023a728f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "households",
        sa.Column(
            "country_id", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False
        ),
    )
    op.add_column("households", sa.Column("default_year", sa.Integer(), nullable=True))
    op.add_column(
        "households",
        sa.Column("canonicalization_version", sa.Integer(), nullable=False),
    )
    op.add_column(
        "households",
        sa.Column(
            "content_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
    )
    op.alter_column(
        "households",
        "household_data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_households_country"), table_name="households")
    op.create_index(
        "ix_households_country_default_year_created_id",
        "households",
        ["country_id", "default_year", "created_at", "id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_households_canonicalization_content_hash",
        "households",
        ["canonicalization_version", "content_hash"],
    )
    op.create_unique_constraint(
        "uq_households_id_country", "households", ["id", "country_id"]
    )
    op.drop_constraint(op.f("ck_households_year"), "households", type_="check")
    op.create_check_constraint(
        op.f("ck_households_canonicalization_version"),
        "households",
        "canonicalization_version > 0",
    )
    op.create_check_constraint(
        op.f("ck_households_content_hash_length"),
        "households",
        "length(content_hash) = 64",
    )
    op.create_check_constraint(
        op.f("ck_households_country"), "households", "country_id IN ('us', 'uk')"
    )
    op.create_check_constraint(
        op.f("ck_households_default_year"),
        "households",
        "default_year IS NULL OR default_year BETWEEN 1900 AND 2200",
    )
    op.drop_column("households", "country")
    op.drop_column("households", "label")
    op.drop_column("households", "year")
    op.drop_constraint(
        op.f("fk_reports_household_id_households"), "reports", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_reports_household_id_households"),
        "reports",
        "households",
        ["household_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "user_household_associations",
        sa.Column(
            "country_id", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False
        ),
    )
    op.add_column(
        "user_household_associations",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    )
    op.add_column(
        "user_household_associations",
        sa.Column("description", sa.Text(), nullable=True),
    )
    op.drop_constraint(
        op.f("uq_user_household_associations_user_household"),
        "user_household_associations",
        type_="unique",
    )
    op.create_index(
        "ix_user_households_country_household",
        "user_household_associations",
        ["country_id", "household_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_households_country_user_created_id",
        "user_household_associations",
        ["country_id", "user_id", "created_at", "id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_user_household_associations_id_country",
        "user_household_associations",
        ["id", "country_id"],
    )
    op.drop_constraint(
        op.f("fk_user_household_associations_household_id_households"),
        "user_household_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_user_household_associations_household_country",
        "user_household_associations",
        "households",
        ["household_id", "country_id"],
        ["id", "country_id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        op.f("ck_user_household_associations_country"),
        "user_household_associations",
        "country_id IN ('us', 'uk')",
    )
    op.drop_column("user_household_associations", "country")
    op.drop_column("user_household_associations", "label")
    op.create_table(
        "legacy_household_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "country_id", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False
        ),
        sa.Column("legacy_household_id", sa.BigInteger(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_api_version",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("fingerprint_version", sa.Integer(), nullable=False),
        sa.Column(
            "fingerprint_sha256",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.CheckConstraint(
            "country_id IN ('us', 'uk')",
            name=op.f("ck_legacy_household_mappings_country"),
        ),
        sa.CheckConstraint(
            "fingerprint_version > 0",
            name=op.f("ck_legacy_household_mappings_fingerprint_version"),
        ),
        sa.CheckConstraint(
            "length(fingerprint_sha256) = 64",
            name=op.f("ck_legacy_household_mappings_fingerprint_length"),
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "country_id"],
            ["households.id", "households.country_id"],
            name="fk_legacy_household_mappings_household_country",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legacy_household_mappings")),
        sa.UniqueConstraint(
            "country_id",
            "legacy_household_id",
            name="uq_legacy_household_mappings_country_legacy",
        ),
    )
    op.create_index(
        "ix_legacy_household_mappings_household",
        "legacy_household_mappings",
        ["household_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_legacy_household_mappings_household", table_name="legacy_household_mappings"
    )
    op.drop_table("legacy_household_mappings")
    op.add_column(
        "user_household_associations",
        sa.Column("label", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_household_associations",
        sa.Column(
            "country", sa.VARCHAR(length=16), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("ck_user_household_associations_country"),
        "user_household_associations",
        type_="check",
    )
    op.drop_constraint(
        "fk_user_household_associations_household_country",
        "user_household_associations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_household_associations_household_id_households"),
        "user_household_associations",
        "households",
        ["household_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "uq_user_household_associations_id_country",
        "user_household_associations",
        type_="unique",
    )
    op.drop_index(
        "ix_user_households_country_user_created_id",
        table_name="user_household_associations",
    )
    op.drop_index(
        "ix_user_households_country_household", table_name="user_household_associations"
    )
    op.create_unique_constraint(
        op.f("uq_user_household_associations_user_household"),
        "user_household_associations",
        ["user_id", "household_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("user_household_associations", "description")
    op.drop_column("user_household_associations", "name")
    op.drop_column("user_household_associations", "country_id")
    op.drop_constraint(
        op.f("fk_reports_household_id_households"), "reports", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_reports_household_id_households"),
        "reports",
        "households",
        ["household_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "households",
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "households",
        sa.Column("label", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "households",
        sa.Column(
            "country", sa.VARCHAR(length=16), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(op.f("ck_households_default_year"), "households", type_="check")
    op.drop_constraint(op.f("ck_households_country"), "households", type_="check")
    op.drop_constraint(
        op.f("ck_households_content_hash_length"), "households", type_="check"
    )
    op.drop_constraint(
        op.f("ck_households_canonicalization_version"), "households", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_households_year"), "households", "year >= 1900 AND year <= 2200"
    )
    op.drop_constraint("uq_households_id_country", "households", type_="unique")
    op.drop_constraint(
        "uq_households_canonicalization_content_hash", "households", type_="unique"
    )
    op.drop_index(
        "ix_households_country_default_year_created_id", table_name="households"
    )
    op.create_index(
        op.f("ix_households_country"), "households", ["country"], unique=False
    )
    op.alter_column(
        "households",
        "household_data",
        existing_type=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_column("households", "content_hash")
    op.drop_column("households", "canonicalization_version")
    op.drop_column("households", "default_year")
    op.drop_column("households", "country_id")
    # ### end Alembic commands ###
