"""remove stage 8 validation data

Revision ID: 8b8ee7fe26bb
Revises: 56dcd15a3afd
Create Date: 2026-08-18 22:30:18.333006
Generation: uv run alembic -c alembic-v2.ini revision --autogenerate
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "8b8ee7fe26bb"
down_revision: Union[str, None] = "56dcd15a3afd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.v2_reference_row_change(
        "tax_benefit_model_versions",
        key={
            "model_id": "80000000-0000-4000-8000-000000000001",
            "version": "stage8-platform-validation",
        },
        before={
            "created_at": "2026-08-14T00:00:00+00:00",
            "description": "Stage 8 generated data-migration validation row.",
            "id": "80000000-0000-4000-8000-000000000002",
            "model_id": "80000000-0000-4000-8000-000000000001",
            "version": "stage8-platform-validation",
        },
        after=None,
    )
    op.v2_reference_row_change(
        "tax_benefit_models",
        key={"name": "stage8-platform-validation"},
        before={
            "created_at": "2026-08-14T00:00:00+00:00",
            "description": "Stage 8 migration lifecycle validation; canonical metadata is introduced in Stage 9.",
            "id": "80000000-0000-4000-8000-000000000001",
            "name": "stage8-platform-validation",
            "updated_at": "2026-08-14T00:00:00+00:00",
        },
        after=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.v2_reference_row_change(
        "tax_benefit_models",
        key={"name": "stage8-platform-validation"},
        before=None,
        after={
            "created_at": "2026-08-14T00:00:00+00:00",
            "description": "Stage 8 migration lifecycle validation; canonical metadata is introduced in Stage 9.",
            "id": "80000000-0000-4000-8000-000000000001",
            "name": "stage8-platform-validation",
            "updated_at": "2026-08-14T00:00:00+00:00",
        },
    )
    op.v2_reference_row_change(
        "tax_benefit_model_versions",
        key={
            "model_id": "80000000-0000-4000-8000-000000000001",
            "version": "stage8-platform-validation",
        },
        before=None,
        after={
            "created_at": "2026-08-14T00:00:00+00:00",
            "description": "Stage 8 generated data-migration validation row.",
            "id": "80000000-0000-4000-8000-000000000002",
            "model_id": "80000000-0000-4000-8000-000000000001",
            "version": "stage8-platform-validation",
        },
    )
    # ### end Alembic commands ###
