"""add Stage 12 observability identifier

Revision ID: 91af4fc8d8c1
Revises: 60d6518b6a98
Create Date: 2026-09-23 18:30:00.000000
Generation: uv run alembic -c alembic-v2.ini revision --autogenerate
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "91af4fc8d8c1"
down_revision: Union[str, None] = "60d6518b6a98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stage12_evaluation_reports",
        sa.Column(
            "observability_id",
            sqlmodel.sql.sqltypes.AutoString(length=36),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stage12_evaluation_reports", "observability_id")
    # ### end Alembic commands ###
