"""map legacy users to v2 uuids

Revision ID: af34023a728f
Revises: c21c4a807a49
Create Date: 2026-09-01 22:06:28.086723
Generation: uv run alembic -c alembic-v2.ini revision --autogenerate
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "af34023a728f"
down_revision: Union[str, None] = "c21c4a807a49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legacy_user_mappings",
        sa.Column(
            "legacy_user_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_legacy_user_mappings_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("legacy_user_id", name=op.f("pk_legacy_user_mappings")),
        sa.UniqueConstraint("user_id", name="uq_legacy_user_mappings_user_id"),
    )
    op.create_index(
        op.f("ix_legacy_user_mappings_user_id"),
        "legacy_user_mappings",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "user_policies",
        "user_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Uuid(),
        existing_nullable=False,
        # Post-generation correction: PostgreSQL requires an explicit
        # cast when restoring the UUID association foreign key.
        postgresql_using="user_id::uuid",
    )
    op.create_foreign_key(
        op.f("fk_user_policies_user_id_users"),
        "user_policies",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=320), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=320), nullable=False
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_constraint(
        op.f("fk_user_policies_user_id_users"), "user_policies", type_="foreignkey"
    )
    op.alter_column(
        "user_policies",
        "user_id",
        existing_type=sa.Uuid(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
        # Post-generation correction: PostgreSQL requires an explicit
        # cast for the reversible UUID-to-text downgrade.
        postgresql_using="user_id::text",
    )
    op.drop_index(
        op.f("ix_legacy_user_mappings_user_id"), table_name="legacy_user_mappings"
    )
    op.drop_table("legacy_user_mappings")
    # ### end Alembic commands ###
