"""enforce v2 user association ownership

Revision ID: b4c69674dd47
Revises: 6ee725e0c563
Create Date: 2026-08-18 12:25:45.926354
Generation: uv run alembic -c alembic-v2.ini revision --autogenerate
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "b4c69674dd47"
down_revision: Union[str, None] = "6ee725e0c563"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_user_household_associations_user_id_users"),
        "user_household_associations",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_user_policies_user_id_users"),
        "user_policies",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_user_report_associations_user_id_users"),
        "user_report_associations",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_user_simulation_associations_user_id_users"),
        "user_simulation_associations",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_simulation_associations_user_id_users"),
        "user_simulation_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_report_associations_user_id_users"),
        "user_report_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_policies_user_id_users"), "user_policies", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_user_household_associations_user_id_users"),
        "user_household_associations",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
