"""track saved policy mirror revisions

Revision ID: c21c4a807a49
Revises: 711ec2f0a5a5
Create Date: 2026-09-01 19:35:37.381580
Generation: uv run alembic -c alembic-v2.ini revision --autogenerate
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "c21c4a807a49"
down_revision: Union[str, None] = "711ec2f0a5a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "legacy_user_policy_mappings",
        sa.Column(
            "last_applied_source_revision",
            sa.BigInteger(),
            server_default="0",
            nullable=False,
        ),
    )
    op.create_check_constraint(
        op.f("ck_legacy_user_policy_mappings_source_revision"),
        "legacy_user_policy_mappings",
        "last_applied_source_revision >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_legacy_user_policy_mappings_source_revision"),
        "legacy_user_policy_mappings",
        type_="check",
    )
    op.drop_column("legacy_user_policy_mappings", "last_applied_source_revision")
    # ### end Alembic commands ###
