"""establish v2 platform baseline

Revision ID: f5ef4347cb2a
Revises:
Create Date: 2026-08-18 23:42:23.783821
Generation: uv run alembic -c alembic-v2.ini revision --autogenerate
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = "f5ef4347cb2a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dynamics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dynamics")),
    )
    op.create_table(
        "households",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("household_data", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "year BETWEEN 1900 AND 2200", name=op.f("ck_households_year")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_households")),
    )
    op.create_index(
        op.f("ix_households_country"), "households", ["country"], unique=False
    )
    op.create_table(
        "tax_benefit_models",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_benefit_models")),
        sa.UniqueConstraint("name", name="uq_tax_benefit_models_name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False
        ),
        sa.Column(
            "primary_country",
            sqlmodel.sql.sqltypes.AutoString(length=2),
            nullable=False,
        ),
        sa.CheckConstraint(
            "primary_country IN ('us', 'uk')", name=op.f("ck_users_primary_country")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_table(
        "datasets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "storage_path", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("is_output_dataset", sa.Boolean(), nullable=False),
        sa.Column("tax_benefit_model_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "NOT is_output_dataset OR storage_path IS NOT NULL",
            name=op.f("ck_datasets_output_storage_path"),
        ),
        sa.CheckConstraint("year BETWEEN 1900 AND 2200", name=op.f("ck_datasets_year")),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_id"],
            ["tax_benefit_models.id"],
            name=op.f("fk_datasets_tax_benefit_model_id_tax_benefit_models"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
        sa.UniqueConstraint("id", "tax_benefit_model_id", name="uq_datasets_id_model"),
        sa.UniqueConstraint(
            "tax_benefit_model_id", "name", name="uq_datasets_model_name"
        ),
    )
    op.create_index(
        op.f("ix_datasets_tax_benefit_model_id"),
        "datasets",
        ["tax_benefit_model_id"],
        unique=False,
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tax_benefit_model_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_id"],
            ["tax_benefit_models.id"],
            name=op.f("fk_policies_tax_benefit_model_id_tax_benefit_models"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
    )
    op.create_index(
        op.f("ix_policies_tax_benefit_model_id"),
        "policies",
        ["tax_benefit_model_id"],
        unique=False,
    )
    op.create_table(
        "tax_benefit_model_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["tax_benefit_models.id"],
            name=op.f("fk_tax_benefit_model_versions_model_id_tax_benefit_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_benefit_model_versions")),
        sa.UniqueConstraint(
            "model_id", "version", name="uq_tax_benefit_model_versions_model_version"
        ),
    )
    op.create_index(
        op.f("ix_tax_benefit_model_versions_model_id"),
        "tax_benefit_model_versions",
        ["model_id"],
        unique=False,
    )
    op.create_table(
        "user_household_associations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_user_household_associations_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_household_associations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_household_associations")),
        sa.UniqueConstraint(
            "user_id",
            "household_id",
            name="uq_user_household_associations_user_household",
        ),
    )
    op.create_index(
        op.f("ix_user_household_associations_household_id"),
        "user_household_associations",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_household_associations_user_id"),
        "user_household_associations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("tax_benefit_model_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_dataset_versions_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_id"],
            ["tax_benefit_models.id"],
            name=op.f("fk_dataset_versions_tax_benefit_model_id_tax_benefit_models"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_versions")),
        sa.UniqueConstraint(
            "dataset_id", "name", name="uq_dataset_versions_dataset_name"
        ),
    )
    op.create_index(
        op.f("ix_dataset_versions_dataset_id"),
        "dataset_versions",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_versions_tax_benefit_model_id"),
        "dataset_versions",
        ["tax_benefit_model_id"],
        unique=False,
    )
    op.create_table(
        "household_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("request_data", sa.JSON(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("dynamic_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                name="v2_household_job_status",
            ),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["dynamic_id"],
            ["dynamics.id"],
            name=op.f("fk_household_jobs_dynamic_id_dynamics"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
            name=op.f("fk_household_jobs_policy_id_policies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_household_jobs")),
    )
    op.create_index(
        "ix_household_jobs_status_created_at",
        "household_jobs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "parameter_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tax_benefit_model_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_version_id"],
            ["tax_benefit_model_versions.id"],
            name=op.f(
                "fk_parameter_nodes_tax_benefit_model_version_id_tax_benefit_model_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parameter_nodes")),
        sa.UniqueConstraint(
            "tax_benefit_model_version_id",
            "name",
            name="uq_parameter_nodes_model_version_name",
        ),
    )
    op.create_index(
        op.f("ix_parameter_nodes_tax_benefit_model_version_id"),
        "parameter_nodes",
        ["tax_benefit_model_version_id"],
        unique=False,
    )
    op.create_table(
        "parameters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "data_type", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("tax_benefit_model_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_version_id"],
            ["tax_benefit_model_versions.id"],
            name=op.f(
                "fk_parameters_tax_benefit_model_version_id_tax_benefit_model_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parameters")),
        sa.UniqueConstraint(
            "tax_benefit_model_version_id",
            "name",
            name="uq_parameters_model_version_name",
        ),
    )
    op.create_index(
        op.f("ix_parameters_tax_benefit_model_version_id"),
        "parameters",
        ["tax_benefit_model_version_id"],
        unique=False,
    )
    op.create_table(
        "regions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "region_type",
            sa.Enum(
                "national",
                "country",
                "state",
                "congressional_district",
                "constituency",
                "local_authority",
                "city",
                "place",
                name="v2_region_type",
            ),
            nullable=False,
        ),
        sa.Column("requires_filter", sa.Boolean(), nullable=False),
        sa.Column(
            "filter_field", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column(
            "filter_value", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "filter_strategy",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column(
            "parent_code", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "state_code", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True
        ),
        sa.Column(
            "state_name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("tax_benefit_model_id", sa.Uuid(), nullable=False),
        sa.Column("default_dataset_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "NOT requires_filter OR (filter_field IS NOT NULL AND filter_value IS NOT NULL)",
            name=op.f("ck_regions_required_filter_values"),
        ),
        sa.ForeignKeyConstraint(
            ["default_dataset_id", "tax_benefit_model_id"],
            ["datasets.id", "datasets.tax_benefit_model_id"],
            name="fk_regions_default_dataset_model_datasets",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_id"],
            ["tax_benefit_models.id"],
            name=op.f("fk_regions_tax_benefit_model_id_tax_benefit_models"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
        sa.UniqueConstraint(
            "tax_benefit_model_id", "code", name="uq_regions_model_code"
        ),
    )
    op.create_index(
        op.f("ix_regions_default_dataset_id"),
        "regions",
        ["default_dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_regions_tax_benefit_model_id"),
        "regions",
        ["tax_benefit_model_id"],
        unique=False,
    )
    op.create_table(
        "user_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
            name=op.f("fk_user_policies_policy_id_policies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_policies_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_policies")),
        sa.UniqueConstraint(
            "user_id", "policy_id", name="uq_user_policies_user_policy"
        ),
    )
    op.create_index(
        op.f("ix_user_policies_policy_id"), "user_policies", ["policy_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_policies_user_id"), "user_policies", ["user_id"], unique=False
    )
    op.create_table(
        "variables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column(
            "entity", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "data_type", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("possible_values", sa.JSON(), nullable=True),
        sa.Column("default_value", sa.JSON(), nullable=False),
        sa.Column("adds", sa.JSON(), nullable=True),
        sa.Column("subtracts", sa.JSON(), nullable=True),
        sa.Column("tax_benefit_model_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_version_id"],
            ["tax_benefit_model_versions.id"],
            name=op.f(
                "fk_variables_tax_benefit_model_version_id_tax_benefit_model_versions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variables")),
        sa.UniqueConstraint(
            "tax_benefit_model_version_id",
            "name",
            name="uq_variables_model_version_name",
        ),
    )
    op.create_index(
        op.f("ix_variables_tax_benefit_model_version_id"),
        "variables",
        ["tax_benefit_model_version_id"],
        unique=False,
    )
    op.create_table(
        "parameter_values",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("parameter_id", sa.Uuid(), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("dynamic_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "policy_id IS NULL OR dynamic_id IS NULL",
            name=op.f("ck_parameter_values_single_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["dynamic_id"],
            ["dynamics.id"],
            name=op.f("fk_parameter_values_dynamic_id_dynamics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parameter_id"],
            ["parameters.id"],
            name=op.f("fk_parameter_values_parameter_id_parameters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
            name=op.f("fk_parameter_values_policy_id_policies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parameter_values")),
    )
    op.create_index(
        "ix_parameter_values_parameter_period",
        "parameter_values",
        ["parameter_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_table(
        "simulations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "simulation_type",
            sa.Enum("household", "economy", name="v2_simulation_type"),
            nullable=False,
        ),
        sa.Column("dataset_id", sa.Uuid(), nullable=True),
        sa.Column("household_id", sa.Uuid(), nullable=True),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("dynamic_id", sa.Uuid(), nullable=True),
        sa.Column("tax_benefit_model_version_id", sa.Uuid(), nullable=False),
        sa.Column("output_dataset_id", sa.Uuid(), nullable=True),
        sa.Column("region_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "succeeded", "failed", name="v2_simulation_status"
            ),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "filter_field", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column(
            "filter_value", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "filter_strategy",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("household_result", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "(simulation_type = 'household' AND household_id IS NOT NULL AND dataset_id IS NULL) OR (simulation_type = 'economy' AND dataset_id IS NOT NULL AND household_id IS NULL)",
            name=op.f("ck_simulations_type_input"),
        ),
        sa.CheckConstraint(
            "(filter_field IS NULL) = (filter_value IS NULL)",
            name=op.f("ck_simulations_filter_pair"),
        ),
        sa.CheckConstraint(
            "year IS NULL OR year BETWEEN 1900 AND 2200",
            name=op.f("ck_simulations_year"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_simulations_dataset_id_datasets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dynamic_id"],
            ["dynamics.id"],
            name=op.f("fk_simulations_dynamic_id_dynamics"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_simulations_household_id_households"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["output_dataset_id"],
            ["datasets.id"],
            name=op.f("fk_simulations_output_dataset_id_datasets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
            name=op.f("fk_simulations_policy_id_policies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_simulations_region_id_regions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_version_id"],
            ["tax_benefit_model_versions.id"],
            name=op.f(
                "fk_simulations_tax_benefit_model_version_id_tax_benefit_model_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulations")),
    )
    op.create_index(
        "ix_simulations_status_created_at",
        "simulations",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulations_tax_benefit_model_version_id"),
        "simulations",
        ["tax_benefit_model_version_id"],
        unique=False,
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("tax_benefit_model_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=True),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=True),
        sa.Column("household_id", sa.Uuid(), nullable=True),
        sa.Column("dataset_id", sa.Uuid(), nullable=True),
        sa.Column("region_id", sa.Uuid(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "year IS NULL OR year BETWEEN 1900 AND 2200", name=op.f("ck_reports_year")
        ),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_reports_baseline_simulation_id_simulations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_reports_dataset_id_datasets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_reports_household_id_households"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
            name=op.f("fk_reports_policy_id_policies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_reports_reform_simulation_id_simulations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_reports_region_id_regions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tax_benefit_model_id"],
            ["tax_benefit_models.id"],
            name=op.f("fk_reports_tax_benefit_model_id_tax_benefit_models"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reports_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        "ix_reports_country_type_created_at",
        "reports",
        ["country", "type", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reports_tax_benefit_model_id"),
        "reports",
        ["tax_benefit_model_id"],
        unique=False,
    )
    op.create_table(
        "user_simulation_associations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("simulation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
            name=op.f("fk_user_simulation_associations_simulation_id_simulations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_simulation_associations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_simulation_associations")),
        sa.UniqueConstraint(
            "user_id",
            "simulation_id",
            name="uq_user_simulation_associations_user_simulation",
        ),
    )
    op.create_index(
        op.f("ix_user_simulation_associations_simulation_id"),
        "user_simulation_associations",
        ["simulation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_simulation_associations_user_id"),
        "user_simulation_associations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "report_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column(
            "country_package_version",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "policyengine_version",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "succeeded", "failed", name="v2_report_run_status"
            ),
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.Enum("initial", "manual", "system", name="v2_report_run_trigger"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("markdown", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status NOT IN ('succeeded', 'failed') OR completed_at IS NOT NULL",
            name=op.f("ck_report_runs_terminal_completion"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_report_runs_report_id_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_runs")),
        sa.UniqueConstraint(
            "report_id", "idempotency_key", name="uq_report_runs_report_idempotency_key"
        ),
    )
    op.create_index(
        "ix_report_runs_current_output",
        "report_runs",
        [
            "report_id",
            "status",
            "country_package_version",
            "policyengine_version",
            "completed_at",
            "id",
        ],
        unique=False,
    )
    op.create_table(
        "user_report_associations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_user_report_associations_report_id_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_report_associations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_report_associations")),
        sa.UniqueConstraint(
            "user_id", "report_id", name="uq_user_report_associations_user_report"
        ),
    )
    op.create_index(
        op.f("ix_user_report_associations_report_id"),
        "user_report_associations",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_report_associations_user_id"),
        "user_report_associations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "aggregates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("simulation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "variable", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "aggregate_type",
            sa.Enum("sum", "mean", "count", name="v2_aggregate_type"),
            nullable=False,
        ),
        sa.Column(
            "entity", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("filter_config", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "succeeded", "failed", name="v2_output_status"
            ),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("result", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_aggregates_report_run_id_report_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
            name=op.f("fk_aggregates_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aggregates")),
    )
    op.create_index(
        "ix_aggregates_report_run_status",
        "aggregates",
        ["report_run_id", "status"],
        unique=False,
    )
    op.create_table(
        "budget_summary",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "variable_name",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=False,
        ),
        sa.Column(
            "entity", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("baseline_total", sa.Float(), nullable=True),
        sa.Column("reform_total", sa.Float(), nullable=True),
        sa.Column("change", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_budget_summary_baseline_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_budget_summary_reform_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_budget_summary_report_run_id_report_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_summary")),
        sa.UniqueConstraint(
            "report_run_id",
            "variable_name",
            "entity",
            name="uq_budget_summary_run_variable_entity",
        ),
    )
    op.create_table(
        "change_aggregates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "variable", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "aggregate_type",
            sa.Enum("sum", "mean", "count", name="v2_aggregate_type"),
            nullable=False,
        ),
        sa.Column(
            "entity", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("filter_config", sa.JSON(), nullable=False),
        sa.Column("change_geq", sa.Float(), nullable=True),
        sa.Column("change_leq", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "succeeded", "failed", name="v2_output_status"
            ),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("result", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_change_aggregates_baseline_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_change_aggregates_reform_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_change_aggregates_report_run_id_report_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_aggregates")),
    )
    op.create_index(
        "ix_change_aggregates_report_run_status",
        "change_aggregates",
        ["report_run_id", "status"],
        unique=False,
    )
    op.create_table(
        "congressional_district_impacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("average_household_income_change", sa.Float(), nullable=False),
        sa.Column("relative_household_income_change", sa.Float(), nullable=False),
        sa.Column("population", sa.Float(), nullable=False),
        sa.Column("district_geoid", sa.Integer(), nullable=False),
        sa.Column("state_fips", sa.Integer(), nullable=False),
        sa.Column("district_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
            name=op.f(
                "fk_congressional_district_impacts_baseline_simulation_id_simulations"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
            name=op.f(
                "fk_congressional_district_impacts_reform_simulation_id_simulations"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_congressional_district_impacts_report_run_id_report_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_congressional_district_impacts")),
        sa.UniqueConstraint(
            "report_run_id",
            "district_geoid",
            name="uq_congressional_district_impacts_run_geoid",
        ),
    )
    op.create_table(
        "constituency_impacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("average_household_income_change", sa.Float(), nullable=False),
        sa.Column("relative_household_income_change", sa.Float(), nullable=False),
        sa.Column("population", sa.Float(), nullable=False),
        sa.Column(
            "constituency_code",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "constituency_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_constituency_impacts_baseline_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_constituency_impacts_reform_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_constituency_impacts_report_run_id_report_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_constituency_impacts")),
        sa.UniqueConstraint(
            "report_run_id",
            "constituency_code",
            name="uq_constituency_impacts_run_code",
        ),
    )
    op.create_table(
        "decile_impacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "income_variable",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=False,
        ),
        sa.Column(
            "entity", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("decile", sa.Integer(), nullable=False),
        sa.Column("quantiles", sa.Integer(), nullable=False),
        sa.Column("baseline_mean", sa.Float(), nullable=True),
        sa.Column("reform_mean", sa.Float(), nullable=True),
        sa.Column("absolute_change", sa.Float(), nullable=True),
        sa.Column("relative_change", sa.Float(), nullable=True),
        sa.Column("count_better_off", sa.Float(), nullable=True),
        sa.Column("count_worse_off", sa.Float(), nullable=True),
        sa.Column("count_no_change", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "decile BETWEEN 1 AND quantiles", name=op.f("ck_decile_impacts_decile")
        ),
        sa.CheckConstraint("quantiles > 0", name=op.f("ck_decile_impacts_quantiles")),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_decile_impacts_baseline_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_decile_impacts_reform_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_decile_impacts_report_run_id_report_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decile_impacts")),
        sa.UniqueConstraint(
            "report_run_id",
            "income_variable",
            "entity",
            "decile",
            "quantiles",
            name="uq_decile_impacts_run_measure",
        ),
    )
    op.create_table(
        "inequality",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("simulation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "income_variable",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=False,
        ),
        sa.Column(
            "entity", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("gini", sa.Float(), nullable=True),
        sa.Column("top_10_share", sa.Float(), nullable=True),
        sa.Column("top_1_share", sa.Float(), nullable=True),
        sa.Column("bottom_50_share", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_inequality_report_run_id_report_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
            name=op.f("fk_inequality_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inequality")),
        sa.UniqueConstraint(
            "report_run_id",
            "simulation_id",
            "income_variable",
            "entity",
            name="uq_inequality_run_simulation_measure",
        ),
    )
    op.create_table(
        "intra_decile_impacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "decile_type",
            sa.Enum("income", "wealth", name="v2_decile_type"),
            nullable=False,
        ),
        sa.Column("decile", sa.Integer(), nullable=False),
        sa.Column("lose_more_than_5pct", sa.Float(), nullable=True),
        sa.Column("lose_less_than_5pct", sa.Float(), nullable=True),
        sa.Column("no_change", sa.Float(), nullable=True),
        sa.Column("gain_less_than_5pct", sa.Float(), nullable=True),
        sa.Column("gain_more_than_5pct", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "decile BETWEEN 0 AND 10", name=op.f("ck_intra_decile_impacts_decile")
        ),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_intra_decile_impacts_baseline_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_intra_decile_impacts_reform_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_intra_decile_impacts_report_run_id_report_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intra_decile_impacts")),
        sa.UniqueConstraint(
            "report_run_id",
            "decile_type",
            "decile",
            name="uq_intra_decile_impacts_run_type_decile",
        ),
    )
    op.create_table(
        "local_authority_impacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("average_household_income_change", sa.Float(), nullable=False),
        sa.Column("relative_household_income_change", sa.Float(), nullable=False),
        sa.Column("population", sa.Float(), nullable=False),
        sa.Column(
            "local_authority_code",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "local_authority_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_local_authority_impacts_baseline_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_local_authority_impacts_reform_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_local_authority_impacts_report_run_id_report_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_local_authority_impacts")),
        sa.UniqueConstraint(
            "report_run_id",
            "local_authority_code",
            name="uq_local_authority_impacts_run_code",
        ),
    )
    op.create_table(
        "poverty",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("simulation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "poverty_type", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "entity", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "filter_variable",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=True,
        ),
        sa.Column("headcount", sa.Float(), nullable=True),
        sa.Column("total_population", sa.Float(), nullable=True),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_poverty_report_run_id_report_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
            name=op.f("fk_poverty_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_poverty")),
    )
    op.create_index(
        "ix_poverty_run_simulation_type",
        "poverty",
        ["report_run_id", "simulation_id", "poverty_type"],
        unique=False,
    )
    op.create_table(
        "program_statistics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("report_run_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_simulation_id", sa.Uuid(), nullable=False),
        sa.Column("reform_simulation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "program_name", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "entity", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("is_tax", sa.Boolean(), nullable=False),
        sa.Column("baseline_total", sa.Float(), nullable=True),
        sa.Column("reform_total", sa.Float(), nullable=True),
        sa.Column("change", sa.Float(), nullable=True),
        sa.Column("baseline_count", sa.Float(), nullable=True),
        sa.Column("reform_count", sa.Float(), nullable=True),
        sa.Column("winners", sa.Float(), nullable=True),
        sa.Column("losers", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["baseline_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_program_statistics_baseline_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reform_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_program_statistics_reform_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_run_id"],
            ["report_runs.id"],
            name=op.f("fk_program_statistics_report_run_id_report_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_statistics")),
        sa.UniqueConstraint(
            "report_run_id",
            "program_name",
            "entity",
            name="uq_program_statistics_run_program_entity",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("program_statistics")
    op.drop_index("ix_poverty_run_simulation_type", table_name="poverty")
    op.drop_table("poverty")
    op.drop_table("local_authority_impacts")
    op.drop_table("intra_decile_impacts")
    op.drop_table("inequality")
    op.drop_table("decile_impacts")
    op.drop_table("constituency_impacts")
    op.drop_table("congressional_district_impacts")
    op.drop_index(
        "ix_change_aggregates_report_run_status", table_name="change_aggregates"
    )
    op.drop_table("change_aggregates")
    op.drop_table("budget_summary")
    op.drop_index("ix_aggregates_report_run_status", table_name="aggregates")
    op.drop_table("aggregates")
    op.drop_index(
        op.f("ix_user_report_associations_user_id"),
        table_name="user_report_associations",
    )
    op.drop_index(
        op.f("ix_user_report_associations_report_id"),
        table_name="user_report_associations",
    )
    op.drop_table("user_report_associations")
    op.drop_index("ix_report_runs_current_output", table_name="report_runs")
    op.drop_table("report_runs")
    op.drop_index(
        op.f("ix_user_simulation_associations_user_id"),
        table_name="user_simulation_associations",
    )
    op.drop_index(
        op.f("ix_user_simulation_associations_simulation_id"),
        table_name="user_simulation_associations",
    )
    op.drop_table("user_simulation_associations")
    op.drop_index(op.f("ix_reports_tax_benefit_model_id"), table_name="reports")
    op.drop_index("ix_reports_country_type_created_at", table_name="reports")
    op.drop_table("reports")
    op.drop_index(
        op.f("ix_simulations_tax_benefit_model_version_id"), table_name="simulations"
    )
    op.drop_index("ix_simulations_status_created_at", table_name="simulations")
    op.drop_table("simulations")
    op.drop_index("ix_parameter_values_parameter_period", table_name="parameter_values")
    op.drop_table("parameter_values")
    op.drop_index(
        op.f("ix_variables_tax_benefit_model_version_id"), table_name="variables"
    )
    op.drop_table("variables")
    op.drop_index(op.f("ix_user_policies_user_id"), table_name="user_policies")
    op.drop_index(op.f("ix_user_policies_policy_id"), table_name="user_policies")
    op.drop_table("user_policies")
    op.drop_index(op.f("ix_regions_tax_benefit_model_id"), table_name="regions")
    op.drop_index(op.f("ix_regions_default_dataset_id"), table_name="regions")
    op.drop_table("regions")
    op.drop_index(
        op.f("ix_parameters_tax_benefit_model_version_id"), table_name="parameters"
    )
    op.drop_table("parameters")
    op.drop_index(
        op.f("ix_parameter_nodes_tax_benefit_model_version_id"),
        table_name="parameter_nodes",
    )
    op.drop_table("parameter_nodes")
    op.drop_index("ix_household_jobs_status_created_at", table_name="household_jobs")
    op.drop_table("household_jobs")
    op.drop_index(
        op.f("ix_dataset_versions_tax_benefit_model_id"), table_name="dataset_versions"
    )
    op.drop_index(op.f("ix_dataset_versions_dataset_id"), table_name="dataset_versions")
    op.drop_table("dataset_versions")
    op.drop_index(
        op.f("ix_user_household_associations_user_id"),
        table_name="user_household_associations",
    )
    op.drop_index(
        op.f("ix_user_household_associations_household_id"),
        table_name="user_household_associations",
    )
    op.drop_table("user_household_associations")
    op.drop_index(
        op.f("ix_tax_benefit_model_versions_model_id"),
        table_name="tax_benefit_model_versions",
    )
    op.drop_table("tax_benefit_model_versions")
    op.drop_index(op.f("ix_policies_tax_benefit_model_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_datasets_tax_benefit_model_id"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("tax_benefit_models")
    op.drop_index(op.f("ix_households_country"), table_name="households")
    op.drop_table("households")
    op.drop_table("dynamics")
    # Post-generation reversibility correction: Alembic drops the columns that
    # use native PostgreSQL enums, but does not remove the schema-level types.
    sa.Enum(name="v2_aggregate_type").drop(op.get_bind())
    sa.Enum(name="v2_decile_type").drop(op.get_bind())
    sa.Enum(name="v2_household_job_status").drop(op.get_bind())
    sa.Enum(name="v2_output_status").drop(op.get_bind())
    sa.Enum(name="v2_region_type").drop(op.get_bind())
    sa.Enum(name="v2_report_run_status").drop(op.get_bind())
    sa.Enum(name="v2_report_run_trigger").drop(op.get_bind())
    sa.Enum(name="v2_simulation_status").drop(op.get_bind())
    sa.Enum(name="v2_simulation_type").drop(op.get_bind())
    # ### end Alembic commands ###
