"""Initial legacy schema

Revision ID: 60d38593ddc3
Revises:
Create Date: 2026-05-11 20:19:44.056995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60d38593ddc3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis",
        sa.Column("prompt_id", sa.INTEGER(), nullable=False),
        sa.Column("prompt", sa.TEXT(), nullable=False),
        sa.Column("analysis", sa.TEXT(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.PrimaryKeyConstraint("prompt_id"),
    )
    op.create_table(
        "computed_household",
        sa.Column("household_id", sa.INTEGER(), nullable=False),
        sa.Column("policy_id", sa.INTEGER(), nullable=False),
        sa.Column("country_id", sa.VARCHAR(length=3), nullable=False),
        sa.Column("api_version", sa.VARCHAR(length=10), nullable=False),
        sa.Column("computed_household_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=32), nullable=True),
        sa.PrimaryKeyConstraint("household_id", "policy_id", "country_id"),
    )
    op.create_table(
        "economy",
        sa.Column("economy_id", sa.INTEGER(), nullable=False),
        sa.Column("policy_id", sa.INTEGER(), nullable=False),
        sa.Column("country_id", sa.VARCHAR(length=3), nullable=False),
        sa.Column("region", sa.VARCHAR(length=32), nullable=True),
        sa.Column("time_period", sa.VARCHAR(length=32), nullable=True),
        sa.Column("options_json", sa.JSON(), nullable=False),
        sa.Column("options_hash", sa.VARCHAR(length=255), nullable=False),
        sa.Column("api_version", sa.VARCHAR(length=10), nullable=False),
        sa.Column("economy_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.Column("message", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("economy_id"),
    )
    op.create_table(
        "household",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("country_id", sa.VARCHAR(length=3), nullable=False),
        sa.Column("label", sa.VARCHAR(length=255), nullable=True),
        sa.Column("api_version", sa.VARCHAR(length=255), nullable=False),
        sa.Column("household_json", sa.JSON(), nullable=False),
        sa.Column("household_hash", sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "legacy_report_output_aliases",
        sa.Column("legacy_report_output_id", sa.INTEGER(), nullable=False),
        sa.Column("canonical_report_output_id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("legacy_report_output_id"),
    )
    op.create_table(
        "policy",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("country_id", sa.VARCHAR(length=3), nullable=False),
        sa.Column("label", sa.VARCHAR(length=255), nullable=True),
        sa.Column("api_version", sa.VARCHAR(length=10), nullable=False),
        sa.Column("policy_json", sa.JSON(), nullable=False),
        sa.Column("policy_hash", sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reform_impact",
        sa.Column("reform_impact_id", sa.INTEGER(), nullable=False),
        sa.Column("baseline_policy_id", sa.INTEGER(), nullable=False),
        sa.Column("reform_policy_id", sa.INTEGER(), nullable=False),
        sa.Column("country_id", sa.VARCHAR(length=3), nullable=False),
        sa.Column("region", sa.VARCHAR(length=32), nullable=False),
        sa.Column("dataset", sa.VARCHAR(length=255), nullable=False),
        sa.Column("time_period", sa.VARCHAR(length=32), nullable=False),
        sa.Column("options_json", sa.JSON(), nullable=False),
        sa.Column("options_hash", sa.VARCHAR(length=255), nullable=False),
        sa.Column("api_version", sa.VARCHAR(length=10), nullable=False),
        sa.Column("reform_impact_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.Column("message", sa.VARCHAR(length=255), nullable=True),
        sa.Column("start_time", sa.DATETIME(), nullable=False),
        sa.Column("end_time", sa.DATETIME(), nullable=True),
        sa.Column("execution_id", sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("reform_impact_id"),
    )
    op.create_table(
        "report_output_runs",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("report_output_id", sa.INTEGER(), nullable=False),
        sa.Column("run_sequence", sa.INTEGER(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column("trigger_type", sa.VARCHAR(length=32), nullable=False),
        sa.Column("requested_at", sa.DATETIME(), nullable=True),
        sa.Column("started_at", sa.DATETIME(), nullable=True),
        sa.Column("finished_at", sa.DATETIME(), nullable=True),
        sa.Column("source_run_id", sa.CHAR(length=36), nullable=True),
        sa.Column("report_spec_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("country_package_version", sa.VARCHAR(length=255), nullable=True),
        sa.Column("policyengine_version", sa.VARCHAR(length=255), nullable=True),
        sa.Column("data_version", sa.VARCHAR(length=255), nullable=True),
        sa.Column("runtime_app_name", sa.VARCHAR(length=255), nullable=True),
        sa.Column("report_cache_version", sa.VARCHAR(length=255), nullable=True),
        sa.Column("simulation_cache_version", sa.VARCHAR(length=255), nullable=True),
        sa.Column("requested_version_override", sa.VARCHAR(length=255), nullable=True),
        sa.Column("resolved_dataset", sa.VARCHAR(length=255), nullable=True),
        sa.Column("resolved_options_hash", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_output_id", "run_sequence"),
    )
    op.create_table(
        "report_outputs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("country_id", sa.VARCHAR(length=3), nullable=False),
        sa.Column("simulation_1_id", sa.INTEGER(), nullable=False),
        sa.Column("simulation_2_id", sa.INTEGER(), nullable=True),
        sa.Column("api_version", sa.VARCHAR(length=10), nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(length=32),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column(
            "year",
            sa.VARCHAR(length=255),
            server_default=sa.text("'2025'"),
            nullable=True,
        ),
        sa.Column("report_kind", sa.VARCHAR(length=64), nullable=True),
        sa.Column("report_spec_json", sa.JSON(), nullable=True),
        sa.Column("report_spec_schema_version", sa.INTEGER(), nullable=True),
        sa.Column("report_spec_status", sa.VARCHAR(length=32), nullable=True),
        sa.Column("active_run_id", sa.CHAR(length=36), nullable=True),
        sa.Column("latest_successful_run_id", sa.CHAR(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "simulation_runs",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("simulation_id", sa.INTEGER(), nullable=False),
        sa.Column("report_output_run_id", sa.CHAR(length=36), nullable=True),
        sa.Column("input_position", sa.INTEGER(), nullable=True),
        sa.Column("run_sequence", sa.INTEGER(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column("trigger_type", sa.VARCHAR(length=32), nullable=False),
        sa.Column("requested_at", sa.DATETIME(), nullable=True),
        sa.Column("started_at", sa.DATETIME(), nullable=True),
        sa.Column("finished_at", sa.DATETIME(), nullable=True),
        sa.Column("source_run_id", sa.CHAR(length=36), nullable=True),
        sa.Column("simulation_spec_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("country_package_version", sa.VARCHAR(length=255), nullable=True),
        sa.Column("policyengine_version", sa.VARCHAR(length=255), nullable=True),
        sa.Column("data_version", sa.VARCHAR(length=255), nullable=True),
        sa.Column("runtime_app_name", sa.VARCHAR(length=255), nullable=True),
        sa.Column("simulation_cache_version", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("simulation_id", "run_sequence"),
    )
    op.create_table(
        "simulations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("country_id", sa.VARCHAR(length=3), nullable=False),
        sa.Column("api_version", sa.VARCHAR(length=10), nullable=False),
        sa.Column("population_id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("population_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("policy_id", sa.INTEGER(), nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(length=32),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column("simulation_spec_json", sa.JSON(), nullable=True),
        sa.Column("simulation_spec_schema_version", sa.INTEGER(), nullable=True),
        sa.Column("active_run_id", sa.CHAR(length=36), nullable=True),
        sa.Column("latest_successful_run_id", sa.CHAR(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tracers",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("household_id", sa.INTEGER(), nullable=False),
        sa.Column("policy_id", sa.INTEGER(), nullable=False),
        sa.Column("country_id", sa.VARCHAR(length=3), nullable=False),
        sa.Column("api_version", sa.VARCHAR(length=10), nullable=False),
        sa.Column("tracer_output", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_policies",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("country_id", sa.VARCHAR(length=3), nullable=False),
        sa.Column("reform_id", sa.INTEGER(), nullable=False),
        sa.Column("reform_label", sa.VARCHAR(length=255), nullable=True),
        sa.Column("baseline_id", sa.INTEGER(), nullable=False),
        sa.Column("baseline_label", sa.VARCHAR(length=255), nullable=True),
        sa.Column("user_id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("year", sa.VARCHAR(length=32), nullable=False),
        sa.Column("geography", sa.VARCHAR(length=255), nullable=False),
        sa.Column("dataset", sa.VARCHAR(length=255), nullable=True),
        sa.Column("number_of_provisions", sa.INTEGER(), nullable=False),
        sa.Column("api_version", sa.VARCHAR(length=32), nullable=False),
        sa.Column("added_date", sa.BIGINT(), nullable=False),
        sa.Column("updated_date", sa.BIGINT(), nullable=False),
        sa.Column("budgetary_impact", sa.VARCHAR(length=255), nullable=True),
        sa.Column("type", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("auth0_id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("username", sa.VARCHAR(length=255), nullable=True),
        sa.Column("primary_country", sa.VARCHAR(length=3), nullable=False),
        sa.Column("user_since", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profiles")
    op.drop_table("user_policies")
    op.drop_table("tracers")
    op.drop_table("simulations")
    op.drop_table("simulation_runs")
    op.drop_table("report_outputs")
    op.drop_table("report_output_runs")
    op.drop_table("reform_impact")
    op.drop_table("policy")
    op.drop_table("legacy_report_output_aliases")
    op.drop_table("household")
    op.drop_table("economy")
    op.drop_table("computed_household")
    op.drop_table("analysis")
    # ### end Alembic commands ###
