"""Add report run canonical schema

Revision ID: 558935decda5
Revises: 60d38593ddc3
Create Date: 2026-05-11 22:21:20.417733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "558935decda5"
down_revision: Union[str, Sequence[str], None] = "60d38593ddc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legacy_report_output_id_map",
        sa.Column("legacy_report_output_id", sa.INTEGER(), nullable=False),
        sa.Column("canonical_report_output_id", sa.INTEGER(), nullable=False),
        sa.Column("display_report_output_run_id", sa.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("legacy_report_output_id"),
    )
    op.create_index(
        "legacy_report_output_id_map_canonical_idx",
        "legacy_report_output_id_map",
        ["canonical_report_output_id"],
        unique=False,
    )
    op.add_column(
        "report_outputs",
        sa.Column("report_identity_hash", sa.VARCHAR(length=64), nullable=True),
    )
    op.add_column(
        "report_outputs",
        sa.Column("report_identity_schema_version", sa.INTEGER(), nullable=True),
    )
    op.create_index(
        "report_outputs_identity_idx",
        "report_outputs",
        ["country_id", "report_identity_hash", "report_identity_schema_version"],
        unique=False,
    )
    op.create_index(
        "simulation_runs_report_output_run_idx",
        "simulation_runs",
        ["report_output_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("simulation_runs_report_output_run_idx", table_name="simulation_runs")
    op.drop_index("report_outputs_identity_idx", table_name="report_outputs")
    op.drop_column("report_outputs", "report_identity_schema_version")
    op.drop_column("report_outputs", "report_identity_hash")
    op.drop_index(
        "legacy_report_output_id_map_canonical_idx",
        table_name="legacy_report_output_id_map",
    )
    op.drop_table("legacy_report_output_id_map")
    # ### end Alembic commands ###
