apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: policyengine-api-v1-otel-collector
  namespace: "${OBSERVABILITY_PROJECT_NUMBER}"
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 30
      serviceAccountName: policyengine-otel-collector@${OBSERVABILITY_PROJECT_ID}.iam.gserviceaccount.com
      containers:
        - name: collector
          image: us-central1-docker.pkg.dev/${OBSERVABILITY_PROJECT_ID}/observability/otel-collector:0.160.0-api-v1-1
          env:
            - name: OBSERVABILITY_PROJECT_ID
              value: ${OBSERVABILITY_PROJECT_ID}
          ports:
            - name: h2c
              containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /
              port: 13133
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 3
