"""separate local tracer and require execution id

Revision ID: 17bb32415f97
Revises: 01e49b3a056e
Create Date: 2026-08-11 18:17:19.903942
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = "17bb32415f97"
down_revision: Union[str, None] = "01e49b3a056e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Production never had this local-only table; fresh baseline schemas do.
    op.drop_table("tracers", if_exists=True)
    op.alter_column(
        "reform_impact",
        "execution_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reform_impact",
        "execution_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.create_table(
        "tracers",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("household_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("policy_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("country_id", mysql.VARCHAR(length=3), nullable=False),
        sa.Column("api_version", mysql.VARCHAR(length=10), nullable=False),
        sa.Column("tracer_output", mysql.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
