"""Stage 12 comparison persistence remains temporary and non-serving."""

from pathlib import Path

from policyengine_api.data.v2.models import V2_METADATA

REPO_ROOT = Path(__file__).resolve().parents[3]
LEGACY_COMPARISON_TABLES = {
    "stage12_evaluation_reports",
    "stage12_evaluation_simulations",
}
COMPARISON_IMPLEMENTATION_MARKERS = LEGACY_COMPARISON_TABLES | {
    "comparison_runs",
    "Stage12ComparisonReport",
    "Stage12ComparisonSimulation",
}


def test_normal_routes_and_services_do_not_read_comparison_tables() -> None:
    source_root = REPO_ROOT / "policyengine_api"
    comparison_root = source_root / "services/v2/comparison_runs"
    internal_route_root = source_root / "fastapi_routes/v2/comparison_runs"
    internal_route_wiring = {
        source_root / "fastapi_routes/dependencies.py",
        source_root / "fastapi_routes/v2/routes.py",
    }
    serving_files = tuple(
        path
        for relative_root in ("routes", "fastapi_routes", "endpoints", "services")
        for path in (source_root / relative_root).rglob("*.py")
        if path.name != "__init__.py"
        and not path.is_relative_to(comparison_root)
        and not path.is_relative_to(internal_route_root)
        and path not in internal_route_wiring
    )

    for path in serving_files:
        source = path.read_text(encoding="utf-8")
        assert not any(
            marker in source for marker in COMPARISON_IMPLEMENTATION_MARKERS
        ), path


def test_production_tables_have_no_comparison_table_dependency() -> None:
    for table_name, table in V2_METADATA.tables.items():
        if table_name in LEGACY_COMPARISON_TABLES:
            continue
        targets = {
            foreign_key.target_fullname
            for column in table.columns
            for foreign_key in column.foreign_keys
        }
        assert not any(
            target.split(".", maxsplit=1)[0] in LEGACY_COMPARISON_TABLES
            for target in targets
        ), table_name


def test_retirement_is_owned_by_a_named_follow_up_change() -> None:
    contract = (REPO_ROOT / "docs/migration/stage-12-worker-contract.md").read_text(
        encoding="utf-8"
    )

    assert "`retire-stage-12-comparison-schema`" in contract
    assert "autogenerated v2 Alembic revision" in contract
    assert "30-day artifact lifecycle" in contract
