runtime: custom
service: policyengine-compute-api
env: flex
resources:
  cpu: 4
  memory_gb: 18
  disk_size_gb: 64
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.9
readiness_check:
  check_interval_sec: 30
  app_start_timeout_sec: 600