"""remove orphaned question table

Revision ID: 01e49b3a056e
Revises: eafc2a547a4e
Create Date: 2026-08-11 16:46:20.938200
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = "01e49b3a056e"
down_revision: Union[str, None] = "eafc2a547a4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Production has this orphaned prototype table; fresh baseline schemas do not.
    op.drop_table("question", if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question",
        sa.Column("question_id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("question", mysql.LONGTEXT(), nullable=False),
        sa.Column("answer", mysql.LONGTEXT(), nullable=True),
        sa.Column("policy_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("country_id", mysql.VARCHAR(length=3), nullable=False),
        sa.Column("subtask", mysql.VARCHAR(length=32), nullable=False),
        sa.Column("status", mysql.VARCHAR(length=32), nullable=False),
        sa.PrimaryKeyConstraint("question_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
