"""add saved policy mirror events

Revision ID: 3d6e8f553ca5
Revises: 1914c0422236
Create Date: 2026-09-01 19:35:29.593649
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "3d6e8f553ca5"
down_revision: Union[str, None] = "1914c0422236"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_policy_mirror_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("country_id", sa.String(length=3), nullable=False),
        sa.Column("legacy_user_policy_id", sa.Integer(), nullable=False),
        sa.Column("source_revision", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=16), nullable=False),
        sa.Column("payload_schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("source_fingerprint_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "event_type IN ('create', 'update')",
            name="ck_user_policy_mirror_events_event_type",
        ),
        sa.CheckConstraint(
            "length(source_fingerprint_sha256) = 64",
            name="ck_user_policy_mirror_events_fingerprint_length",
        ),
        sa.CheckConstraint(
            "payload_schema_version > 0",
            name="ck_user_policy_mirror_events_payload_schema_version",
        ),
        sa.CheckConstraint(
            "source_revision > 0", name="ck_user_policy_mirror_events_source_revision"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "country_id",
            "legacy_user_policy_id",
            "source_revision",
            name="uq_user_policy_mirror_events_source_revision",
        ),
    )
    op.create_index(
        "ix_user_policy_mirror_events_pending_age",
        "user_policy_mirror_events",
        ["processed_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_user_policy_mirror_events_pending_source",
        "user_policy_mirror_events",
        ["country_id", "legacy_user_policy_id", "processed_at", "source_revision"],
        unique=False,
    )
    op.add_column(
        "user_policies",
        sa.Column(
            "mirror_revision",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_policies", "mirror_revision")
    op.drop_index(
        "ix_user_policy_mirror_events_pending_source",
        table_name="user_policy_mirror_events",
    )
    op.drop_index(
        "ix_user_policy_mirror_events_pending_age",
        table_name="user_policy_mirror_events",
    )
    op.drop_table("user_policy_mirror_events")
    # ### end Alembic commands ###
