"""add household mirror events

Revision ID: 7811e0c49301
Revises: 3d6e8f553ca5
Create Date: 2026-09-07 23:40:07.186189
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "7811e0c49301"
down_revision: Union[str, None] = "3d6e8f553ca5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "household_mirror_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("country_id", sa.String(length=3), nullable=False),
        sa.Column("legacy_household_id", sa.Integer(), nullable=False),
        sa.Column("payload_schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("source_fingerprint_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "country_id IN ('us', 'uk')", name="ck_household_mirror_events_country"
        ),
        sa.CheckConstraint(
            "length(source_fingerprint_sha256) = 64",
            name="ck_household_mirror_events_fingerprint_length",
        ),
        sa.CheckConstraint(
            "payload_schema_version > 0",
            name="ck_household_mirror_events_payload_schema_version",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "country_id",
            "legacy_household_id",
            name="uq_household_mirror_events_country_legacy",
        ),
    )
    op.create_index(
        "ix_household_mirror_events_pending_age",
        "household_mirror_events",
        ["processed_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_household_mirror_events_pending_source",
        "household_mirror_events",
        ["country_id", "legacy_household_id", "processed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_household_mirror_events_pending_source",
        table_name="household_mirror_events",
    )
    op.drop_index(
        "ix_household_mirror_events_pending_age", table_name="household_mirror_events"
    )
    op.drop_table("household_mirror_events")
    # ### end Alembic commands ###
